Fix the markup of YAML front matter of _entries/chu-liu-edmonds.md
because the following error message exists:

```
Error: YAML Exception reading /home/user/GitHub/algorithm-encyclopedia/_entries/chu-liu-edmonds.md: (<unknown>): mapping values are not allowed in this context at line 9 column 17
```